name: Build and deploy ASP.Net Core app to Azure Web App - yazdanapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'  # Ensure correct version for your project

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build the Application
        run: dotnet build --configuration Release

      - name: Publish the Application
        run: dotnet publish ./learningapp2/tree/main/LearningApp/LearningApp.csproj.csproj -c Release -o ./publish_output

      - name: Upload Artifact for Deployment
        uses: actions/upload-artifact@v4
        with:
          name: net-app-artifact  # Artifact name must match in upload and download steps
          path: ./publish_output  # Ensure path points to correct directory

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write

    steps:
      - name: Download Artifact from Build Job
        uses: actions/download-artifact@v4
        with:
          name: net-app-artifact  # Ensure matching name in upload step

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_19FD035751B24174ACEF416A83C0F90C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E552159E368D4361AC34881B87156A63 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E22A963B48304CC985413F8EE49CD956 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'yazdanapp'
          package: ./publish_output  # Ensure correct path to artifact
          slot-name: 'production'
