name: Build and deploy ASP.Net Core app to Azure Web App - yazdanapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'  # Set the required version for your project

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build the Application
        run: dotnet build --configuration Release

      - name: Publish the Application
        run: dotnet publish -c Release -o ./publish_output

      - name: Upload Artifact for Deployment
        uses: actions/upload-artifact@v4
        with:
          name: net-app-artifact  # Consistent artifact name
          path: ./publish_output  # Corrected path

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write  # Required for JWT-based Azure authentication

    steps:
      - name: Download Artifact from Build Job
        uses: actions/download-artifact@v4
        with:
          name: net-app-artifact  # Ensure name matches upload step

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'yazdanapp'
          slot-name: 'production'
          package: ./publish_output  # Path to the downloaded artifact
